/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low':      '#f4f4f2',
        'primary-fixed':              '#e5e2e1',
        'on-primary-fixed-variant':   '#474746',
        'primary-container':          '#1c1b1b',
        'on-secondary-container':     '#756100',
        'surface-container-highest':  '#e2e3e1',
        'on-primary':                 '#ffffff',
        'on-tertiary-container':      '#42945b',
        'secondary-container':        '#ffde5e',
        'tertiary-fixed':             '#a0f5b4',
        'surface-dim':                '#dadad8',
        'on-tertiary-fixed':          '#00210c',
        'tertiary-fixed-dim':         '#85d999',
        'on-background':              '#1a1c1b',
        'on-tertiary':                '#ffffff',
        'secondary-fixed':            '#ffe172',
        'on-primary-fixed':           '#1c1b1b',
        'inverse-on-surface':         '#f1f1ef',
        'on-secondary-fixed-variant': '#554600',
        'outline':                    '#747878',
        'tertiary-container':         '#00210c',
        'on-surface-variant':         '#444748',
        'surface-container-lowest':   '#ffffff',
        'secondary':                  '#705d00',
        'on-secondary':               '#ffffff',
        'surface-tint':               '#5f5e5e',
        'error-container':            '#ffdad6',
        'outline-variant':            '#c4c7c7',
        'surface':                    '#f9f9f7',
        'tertiary':                   '#000000',
        'surface-container':          '#eeeeec',
        'on-primary-container':       '#858383',
        'on-error':                   '#ffffff',
        'primary-fixed-dim':          '#c8c6c5',
        'surface-variant':            '#e2e3e1',
        'on-tertiary-fixed-variant':  '#005227',
        'error':                      '#ba1a1a',
        'secondary-fixed-dim':        '#e4c447',
        'inverse-primary':            '#c8c6c5',
        'inverse-surface':            '#2f3130',
        'surface-bright':             '#f9f9f7',
        'on-secondary-fixed':         '#221b00',
        'background':                 '#f9f9f7',
        'surface-container-high':     '#e8e8e6',
        'primary':                    '#000000',
        'on-error-container':         '#93000a',
        'on-surface':                 '#1a1c1b',
        'accent':                     '#E8C84A',
        'rule':                       '#E8E4DF',
        'custom-yellow':              '#E8C84A',
        'custom-green':               '#5BAD72',
        'custom-ivory':               '#FAFAF8',
        'custom-black':               '#1A1A1A',
        'custom-border':              '#E8E4DF',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin:       '32px',
        max_width:    '1024px',
        gutter:       '24px',
        grid_columns: '12',
        section_gap:  '80px',
        base_unit:    '8px',
      },
      fontFamily: {
        'label-caps':       ['"IBM Plex Mono"', 'monospace'],
        'label-mono':       ['"IBM Plex Mono"', 'monospace'],
        'body-md':          ['"Source Sans 3"', 'system-ui', 'sans-serif'],
        'headline-sm':      ['"Playfair Display"', 'Georgia', 'serif'],
        'body-lg':          ['"Source Sans 3"', 'system-ui', 'sans-serif'],
        'display-lg-mobile':['"Playfair Display"', 'Georgia', 'serif'],
        'display-lg':       ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md':      ['"Playfair Display"', 'Georgia', 'serif'],
      },
      fontSize: {
        'label-caps':        ['12px',  { lineHeight: '1.0',  letterSpacing: '0.15em', fontWeight: '500' }],
        'label-mono':        ['13px',  { lineHeight: '1.4',  fontWeight: '400' }],
        'body-md':           ['16px',  { lineHeight: '1.5',  fontWeight: '400' }],
        'headline-sm':       ['24px',  { lineHeight: '1.4',  fontWeight: '400' }],
        'body-lg':           ['18px',  { lineHeight: '1.6',  fontWeight: '400' }],
        'display-lg-mobile': ['40px',  { lineHeight: '1.2',  letterSpacing: '-0.01em', fontWeight: '400' }],
        'display-lg':        ['64px',  { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-md':       ['32px',  { lineHeight: '1.3',  fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
